server: 
  port: 3000
  servlet:
    context-path: /gerenciamentos/pessoas
   
spring:
  application:
    name: gerenciamento-pessoas
  main:
    banner-mode: "OFF"
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciamento_pessoas
    username: valter
    password: 9153_Deus
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        generate_statistics: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      

        